### ISSUE TITLE
Issues of password aging module

### ISSUE THREAD

**Issue by kkeshav** [stivesso/password_aging#8]
Hello,

I've installed password_aging module and I'm trying deploy in the client server, but I'm getting below mentioned error.

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not match | at /etc/puppetlabs/puppet/environments/*****/modules/common/password_aging/manifests/init.pp:64

Note : I've puppetlabs-stdlib (v4.11.0) installed.

**Comment by stivesso** [comment]
Hello kkeshav,

What is your puppet master version?

**Comment by kkeshav** [comment]
Hello Stive,

If is 3.x.

Regards
Karthik

**Comment by kkeshav** [comment]
It is 3.8

Regards,
Karthik

**Comment by stivesso** [comment]
Hi kkeshav,

The error is a syntax error due to loop structure that is available on Puppet 4 Parser. That can be fixed in your 3.8 environment by enabling future parser, check here for details on how to enable future parser in 3.8: [https://docs.puppet.com/puppet/3.8/reference/experiments_future.html#enabling-the-future-parser](https://docs.puppet.com/puppet/3.8/reference/experiments_future.html#enabling-the-future-parser) 
I will also update the documentation and enforce that check, 
Thanks

**Comment by kkeshav** [comment]
Hello Stive,

Thanks, It worked, but my concern is since we are using version 3.8 if we enable parser=future, there is a chance of breaking all our existing code rite? I read that in one of link.

Regards,
Karthik

**Comment by stivesso** [comment]
It is indeed a change that must be assessed. But there's a small guideline that you can use to ease that assessment, more details about that [here](https://docs.puppet.com/puppet/3.8/reference/experiments_future.html#whats-tricky-about-switching-to-the-future-parser). I'm also suggesting that if you use directory environments, then first complete that modification in your "test" environment. Details for enabling future parser for a specific environment is available [here](https://docs.puppet.com/puppet/3.8/reference/experiments_future.html#enabling-the-future-parser)
